file = open("labfile.txt","w")
file.write("hello world!\n")
file.write("this is a new line\n")
file = open("labfile.txt","r")
content=file.read()
print(content)
file.close()
file=open("labfile.txt","w")
file.write("new file")
file.close()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             